### ISSUE TITLE
using on Windows 10

### ISSUE THREAD

**Issue by ve3gtc** [mahtin/tinyGS-antenna-map#1]
This application will run on Win10 using Python 3 ( tested on python 3.9.5 ) but will need a couple of changes.

Specifically in packets.py

around line 101 change from:

with open(PacketFileProcessing.DATA_DIRECTORY + '/' + station_name + '/' + filename, 'r') as fd:

to:

with open(PacketFileProcessing.DATA_DIRECTORY + '/' + station_name + '/' + filename, 'r', encoding="utf8") as fd:

This specifies using utf-8 encoding when calling json.load(fd).  This likely will OK when used on linux as well.

next change is around line 260. Win10 does not like file names containing : 
My change was simply to change to:

		filename = now.strftime('%Y%m%d_%H%M') + '.packets.json'

Maybe not as intuitive a filename as originally coded but Win10 is now happy with the file name

Other than that, following your instructions and creating .user_id file and a /data folder the application now executes without error and creates a nice .png file.

Well done, save me the work of creating my own app.

cheers, Graham ve3gtc  ( ve3gtc_tinyGS )

**Comment by mahtin** [comment]
Thank you! Merged and credit provided!
